/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package at.escapedoom.data.rest.api;

import at.escapedoom.data.rest.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "Template", description = "the Template API")
public interface TemplateApi {

    default TemplateApiDelegate getDelegate() {
        return new TemplateApiDelegate() {
        };
    }

    /**
     * POST /templates : Creates a new Template for Escape Doom Game Creates a new Template for
     *
     * @param templateCreateRequestDTO
     *            Lectors ID + Name and Description for a Template (required)
     *
     * @return The basic template component (status code 200) or Bad Request (status code 400) or Internal Server Error
     *         (status code 500)
     */
    @Operation(operationId = "createTemplate", summary = "Creates a new Template for Escape Doom Game", description = "Creates a new Template for", tags = {
            "Template" }, responses = {
                    @ApiResponse(responseCode = "200", description = "The basic template component", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TemplateDTO.class)) }),
                    @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateBadRequestDTO.class)) }),
                    @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateInternalServerErrorDTO.class)) }) })
    @RequestMapping(method = RequestMethod.POST, value = "/templates", produces = { "application/json" }, consumes = {
            "application/json" })

    default ResponseEntity<TemplateDTO> createTemplate(
            @Parameter(name = "TemplateCreateRequestDTO", description = "Lectors ID + Name and Description for a Template", required = true) @Valid @RequestBody TemplateCreateRequestDTO templateCreateRequestDTO) {
        return getDelegate().createTemplate(templateCreateRequestDTO);
    }

    /**
     * DELETE /templates/{template-id} : Deletes an Template Deletes an Template by its unique ID
     *
     * @param templateId
     *            The unique ID of the Template to delete (required)
     *
     * @return Operation result for Template (status code 200) or Bad Request (status code 400) or Not Found (status
     *         code 404) or Internal Server Error (status code 500)
     */
    @Operation(operationId = "deleteTemplate", summary = "Deletes an Template", description = "Deletes an Template by its unique ID", tags = {
            "Template" }, responses = {
                    @ApiResponse(responseCode = "200", description = "Operation result for Template", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TemplateResultDTO.class)) }),
                    @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateBadRequestDTO.class)) }),
                    @ApiResponse(responseCode = "404", description = "Not Found", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateNotFoundDTO.class)) }),
                    @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateInternalServerErrorDTO.class)) }) })
    @RequestMapping(method = RequestMethod.DELETE, value = "/templates/{template-id}", produces = {
            "application/json" })

    default ResponseEntity<TemplateResultDTO> deleteTemplate(
            @Parameter(name = "template-id", description = "The unique ID of the Template to delete", required = true, in = ParameterIn.PATH) @PathVariable("template-id") String templateId) {
        return getDelegate().deleteTemplate(templateId);
    }

    /**
     * GET /templates : Get all Templates Retrieve a list of all existing Templates from a Lector
     *
     * @return A list of templates (status code 200) or Internal Server Error (status code 500)
     */
    @Operation(operationId = "getAllTemplates", summary = "Get all Templates", description = "Retrieve a list of all existing Templates from a Lector", tags = {
            "Template" }, responses = {
                    @ApiResponse(responseCode = "200", description = "A list of templates", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TemplateDTO.class))) }),
                    @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateInternalServerErrorDTO.class)) }) })
    @RequestMapping(method = RequestMethod.GET, value = "/templates", produces = { "application/json" })

    default ResponseEntity<List<TemplateDTO>> getAllTemplates(

    ) {
        return getDelegate().getAllTemplates();
    }

    /**
     * GET /templates/{template-id} : Get a specific Template by ID Retrieve details of a specific Template using its
     * unique ID
     *
     * @param templateId
     *            The unique ID of the Template (required)
     *
     * @return Details of the specified template (status code 200) or Template not found (status code 404) or Internal
     *         Server Error (status code 500)
     */
    @Operation(operationId = "getTemplate", summary = "Get a specific Template by ID", description = "Retrieve details of a specific Template using its unique ID", tags = {
            "Template" }, responses = {
                    @ApiResponse(responseCode = "200", description = "Details of the specified template", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TemplateDTO.class)) }),
                    @ApiResponse(responseCode = "404", description = "Template not found", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = GetTemplateNotFoundDTO.class)) }),
                    @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateInternalServerErrorDTO.class)) }) })
    @RequestMapping(method = RequestMethod.GET, value = "/templates/{template-id}", produces = { "application/json" })

    default ResponseEntity<TemplateDTO> getTemplate(
            @Parameter(name = "template-id", description = "The unique ID of the Template", required = true, in = ParameterIn.PATH) @PathVariable("template-id") String templateId) {
        return getDelegate().getTemplate(templateId);
    }

    /**
     * PUT /templates/{template-id} : Overrides an existing Template Override the name, description, and levels of an
     * existing Template
     *
     * @param templateId
     *            The unique ID of the Template to update (required)
     * @param templateUpdateRequestDTO
     *            The updated data for the template (required)
     *
     * @return Template updated successfully (status code 200) or Bad Request (status code 400) or Not Found (status
     *         code 404) or Internal Server Error (status code 500)
     */
    @Operation(operationId = "putTemplate", summary = "Overrides an existing Template", description = "Override the name, description, and levels of an existing Template", tags = {
            "Template" }, responses = {
                    @ApiResponse(responseCode = "200", description = "Template updated successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TemplateUpdateResultDTO.class)) }),
                    @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateBadRequestDTO.class)) }),
                    @ApiResponse(responseCode = "404", description = "Not Found", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateNotFoundDTO.class)) }),
                    @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = CreateInternalServerErrorDTO.class)) }) })
    @RequestMapping(method = RequestMethod.PUT, value = "/templates/{template-id}", produces = {
            "application/json" }, consumes = { "application/json" })

    default ResponseEntity<TemplateUpdateResultDTO> putTemplate(
            @Parameter(name = "template-id", description = "The unique ID of the Template to update", required = true, in = ParameterIn.PATH) @PathVariable("template-id") String templateId,
            @Parameter(name = "TemplateUpdateRequestDTO", description = "The updated data for the template", required = true) @Valid @RequestBody TemplateUpdateRequestDTO templateUpdateRequestDTO) {
        return getDelegate().putTemplate(templateId, templateUpdateRequestDTO);
    }

}
