apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gw-ing
  labels:
    {{- include "escape-doom.labels" . | nindent 4 }}
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: helmheim.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 8081
  tls:
    - secretName: helmheim-tls
      hosts:
        - helmheim.de