spring:
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: player_schema
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: playerapi
    password: escapedoom
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: player_schema
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9081/realms/escape-doom/protocol/openid-connect/certs

server:
  port: 8092
  servlet:
    context-path: /leaderboard-api


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"