spring:
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: leaderboard_schema
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: leaderboardapi
    password: escapedoom
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: leaderboard_schema
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9081/realms/escape-doom/protocol/openid-connect/certs

server:
  port: 8092
  servlet:
    context-path: /leaderboard-api

escapedoom:
  communication:
    session-api-url: http://localhost:8081/session-api/v1


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"