/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package at.escapedoom.player.rest.api;

import at.escapedoom.player.rest.model.EscapeRoomJoin;
import at.escapedoom.player.rest.model.EscapeRoomJoinResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "lobby", description = "the lobby API")
public interface LobbyApi {

    default LobbyApiDelegate getDelegate() {
        return new LobbyApiDelegate() {
        };
    }

    /**
     * PUT /join : Join an escape-room instance Join an escape-room instance
     *
     * @param escapeRoomJoin
     *            The escape-room instance to join (required)
     *
     * @return OK (status code 200)
     */
    @Operation(operationId = "joinPut", summary = "Join an escape-room instance", description = "Join an escape-room instance", tags = {
            "lobby" }, responses = { @ApiResponse(responseCode = "200", description = "OK", content = {
                    @Content(mediaType = "application/json", schema = @Schema(implementation = EscapeRoomJoinResponse.class)) }) })
    @RequestMapping(method = RequestMethod.PUT, value = "/join", produces = { "application/json" }, consumes = {
            "application/json" })

    default ResponseEntity<EscapeRoomJoinResponse> joinPut(
            @Parameter(name = "EscapeRoomJoin", description = "The escape-room instance to join", required = true) @Valid @RequestBody EscapeRoomJoin escapeRoomJoin) {
        return getDelegate().joinPut(escapeRoomJoin);
    }

}
