/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package at.escapedoom.session.rest.api;

import at.escapedoom.session.rest.model.SessionResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "session", description = "the session API")
public interface SessionApi {

    default SessionApiDelegate getDelegate() {
        return new SessionApiDelegate() {
        };
    }

    /**
     * GET /session/tags/{tag} : Get all escape-room instances with a specific tag Retrieves a list of escape-room
     * instances filtered by a single tag
     *
     * @param tag
     *            The tag to filter sessions by (required)
     *
     * @return OK (status code 200)
     */
    @Operation(operationId = "getERByTag", summary = "Get all escape-room instances with a specific tag", description = "Retrieves a list of escape-room instances filtered by a single tag", tags = {
            "session" }, responses = { @ApiResponse(responseCode = "200", description = "OK", content = {
                    @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SessionResponse.class))) }) })
    @RequestMapping(method = RequestMethod.GET, value = "/session/tags/{tag}", produces = { "application/json" })

    default ResponseEntity<List<SessionResponse>> getERByTag(
            @Parameter(name = "tag", description = "The tag to filter sessions by", required = true, in = ParameterIn.PATH) @PathVariable("tag") String tag) {
        return getDelegate().getERByTag(tag);
    }

    /**
     * GET /session/pins/{pin} : Retrieve an escape-room session by room pin Fetches an escape-room session using its
     * room pin
     *
     * @param pin
     *            The 6-digit room pin (required)
     *
     * @return OK (status code 200)
     */
    @Operation(operationId = "getERSessionByPin", summary = "Retrieve an escape-room session by room pin", description = "Fetches an escape-room session using its room pin", tags = {
            "session" }, responses = { @ApiResponse(responseCode = "200", description = "OK", content = {
                    @Content(mediaType = "application/json", schema = @Schema(implementation = SessionResponse.class)) }) })
    @RequestMapping(method = RequestMethod.GET, value = "/session/pins/{pin}", produces = { "application/json" })

    default ResponseEntity<SessionResponse> getERSessionByPin(
            @Min(100000) @Max(999999) @Parameter(name = "pin", description = "The 6-digit room pin", required = true, in = ParameterIn.PATH) @PathVariable("pin") Integer pin) {
        return getDelegate().getERSessionByPin(pin);
    }

}
