spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: sessionapi
    password: escapedoom
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: session_schema
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9081/realms/escape-doom/protocol/openid-connect/certs

server:
  port: 8094
  servlet:
    context-path: /session-api


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

escapedoom:
  redis:
    host: localhost
    port: 6379