spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: player_schema
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: playerapi
    password: escapedoom
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: player_schema
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9081/realms/escape-doom/protocol/openid-connect/certs

server:
  port: 8093
  servlet:
    context-path: /player-api


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

escapedoom:
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.server: DEBUG
    org.springframework.web.socket.client: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.springframework.web.socket.handler: DEBUG