on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Fix Permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - name: Build and Push Image with Jib
        run: mvn compile  -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} jib:build -pl services/gateway-service,services/data-service,services/session-service,services/player-service,services/leaderboard-service --file pom.xml
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./frontend
        run: |
          IMAGE_NAME=ghcr.io/megamxl/escape-doom-microservices/frontend:latest
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME
