on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - name: Build and Push Image with Jib
        run: mvn compile -Dmaven.multiModuleProjectDirectory=. jib:build -pl services/gateway-service,services/data-service --file pom.xml
        env:
          JIB_REGISTRY_USERNAME: ${{ github.actor }}
          JIB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}