on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - name: Build and Push Image with Jib
        run: mvn compile  -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} jib:build -pl services/gateway-service,services/data-service,services/session-service,services/player-service,services/leaderboard-service --file pom.xml

  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: kubb it
        working-directory: ./frontend
        run: npm run gen && npm run format
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./frontend
        run: |
          IMAGE_NAME=ghcr.io/megamxl/escape-doom-microservices/frontend:latest
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME

      - name: Build and push Dev-Docker image
        working-directory: ./frontend
        run: |
          IMAGE_NAME=ghcr.io/megamxl/escape-doom-microservices/dev-frontend:latest
              docker build -f Dockerfile-dev -t $IMAGE_NAME .
              docker push $IMAGE_NAME